### ISSUE TITLE
Is this compatible with 22.04 ?

### ISSUE THREAD

**Issue by cofeeys** [51n7/kTile#2]
Hello, I have activated the script, but I can't open the GUI (CTRL + .) and the shortcuts aren't available in the shortcut tab .
Maybe because of my kubuntu version ?

![image](https://user-images.githubusercontent.com/34076733/220599005-0a0b6a32-dd25-4bf9-965a-1825a9482547.png)

**Comment by 51n7** [comment]
hm.. I have not tested on Kubuntu but I know this script has an issue with KDE Neon which also uses a Ubuntu base, the fix in KDE Neon is to just add the missing dependency:
```
sudo pkcon install qml-module-qtquick-localstorage
```
I'll grab a VM and test Kubuntu.

**Comment by 51n7** [comment]
Confirmed, the same issue is in Kubuntu so you just need to run the following command:
(and probably log out/in)
```
sudo apt-get install qml-module-qtquick-localstorage
```
Thanks for catching this @PlasMania as it's hard to test every distro. I will update the docs to note this fix.
